substitutions:
  _SERVICE: "finalyoutube"
  _REGION: "us-central1"
steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$SHORT_SHA",
      "."
    ]
images:
- "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$SHORT_SHA"
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    [
      "-c",
      "gcloud run deploy $_SERVICE \
         --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$SHORT_SHA \
         --region=$_REGION \
         --platform=managed \
         --allow-unauthenticated"
    ]
timeout: "600s"
